// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldtlumluapgapsbwlvuu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkdGx1bWx1YXBnYXBzYndsdnV1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1NzYyMDMsImV4cCI6MjA2MTE1MjIwM30.FuHNchnbaTXLjZqXIy9Gr4iB2cJdlxWVVRVPVpVcGs8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);